### PR TITLE
 Front-End Lambda Notes Project

### PR DESCRIPTION
**Pull request by ashleijo**
## Trello Set Up:
* [x] Create a Trello account
* [x] Create a new board called "Lambda Notes - {Your Name}"
* [x] Create lists titled `backlog`,`To Do`, `In Progress`, and `Done`.
* [x] Fill in the `To Do` list with the MVP features listed below
* [x] Fill in the `backlog` list with all the extra features listed below
* [x] Share your board with the Project Manager that has been assigned to you.  If you have not been assigned yet, reach out to your lead TA for guidance.
* [x] Add your Trello URL to your project's README.md file. Commit the change, push it to your Repository & Submit a Pull Request

## MVP Features:
* [x] Display a list of notes
* [x] Create a note with a title and content
* [x] View an existing note
* [x] Delete an existing note
* [x] Edit an existing note

## Extra Features:
* [x] Make the data persist with arrays / object literals (JSON) or a 3rd party service like Firebase
* [x] Export all notes to a CSV
* [x] Drag sorting in the list view
* [ ] Search functionality
* [ ] Markdown support in notes
* [ ] Sorting options in the list view
* [ ] Create and display tags that can be added to notes
* [ ] Add the ability to have checklists within the note view
* [ ] Create a login system around the MVP

### CODE REVIEW

**Comment by mixelpixel** [comment]
# Looks great so far. How's it coming along on your end?

**Comment by mixelpixel** [comment]
# THOUGHTS ON GIT COMMIT MESSAGES.

1. Let your git commit message titles _tell the story of your development process_. No one is expecting a novel, but some succinct _Hemingway-esque_ prose describing the state of your project as you construct discrete modules, functions, add features, _et cetera_ will
    - Help your analytical thinking.
    - Let your development team quickly ssess your work
    - Help you find stuff you may have worked over which you might want to revisit

2. It is GREAT that you are committing often. If you want to add additional comments and details to your git commit messages, you can **add a body to your commit messages** by adding a "newline" after the title and then all the additional info you care to include, e.g.

```
Git commit TITLE less than 50 (to 72) characters.

Git commit BODY which can contain as much pertinent information and descriptions as you see fit. Some development teams like tons and tons of information, and depending on the scope of the commit, it may be necessary to make lots of deatiled notes - especially in projects like React where there can be a vast amount of files and a complex architecture.
1) I did this
2) I did that
3) this worked well
4) this didn't
5) et alii
```

If you follow the above format, your `git log` will be easier to read, and, on GitHub in the Pull Requests, the body will be accessible by clicking on the three little dots:

screen shot 2018-02-10 at 9 06 14 pm

...such that they will reveal the BODY. This let's teammates, project leads, managers, as well as TAs Instructors, your classmates and whomever quickly evaluate your development process; your investigation; _your thinking_ - and if need be, dive in a little deeper. Also, this practice will really help _your thinking_ and _your recall_ after you've stepped away from a project for days or weeks or months and years.

screen shot 2018-02-10 at 9 06 32 pm

**Comment by ashleijo** [comment]
It's going O.K. I think. Some things took a bit more time than I expected, but I'm back on track. I'll work on adding a new note next.

**Comment by mixelpixel** [comment]
Nice. Hopefully this project will have the additional benefit of giving students a baseline for making useful predictions about how long it will take to complete objectives :)

**Comment by mixelpixel** [comment]
I've added the Trello Set-up steps to your first PR comment and checked off the ones I see completed. Josh added these to the project README.md after releasing the Lambda School GitHub repo to the class.

You don't **_need_** the update to the Lambda School repositories README.md, but, as far as GIT is concerned, do you have a clear vision of _**how**_ you might use Git to "add" to your local repository another "remote" alias for the Lambda School GitHub URL, such that you could `git pull upstream master` or if you prefer, `git pull lambda master`?

**Comment by ashleijo** [comment]
Yeah, I actually had already pulled his changes-- I just didn't update this checklist comment on the PR. Everything should be good now. Thank you for the help.

**Comment by ashleijo** [comment]
I think this is ready for an MVP review. Until then, I'll keep styling and tweaking things on my own.

**Comment by mixelpixel** [comment]
@ashleijo Would you be so kind as to include your Trello URL in the README.md file? Also, Manisha Lal will be your Project Manager for the rest of the week. Could you either add her to your Trello board, or make the board public so she has access? Thank you 😄

**Comment by ashleijo** [comment]
The trello url is in lambdanotes/README.md but I will move it to the main directory's README.md.

**Comment by manishavi** [comment]
Hey Ashlie,
Good work doing git commits and pushing up the changes.
I downloaded your project and ran it in the browser.Great job on your project and showcasing your progress. The functionality of your app looks good.
Nice work so far and you are ready to move further to work on extra features.

-Manisha

**Comment by mixelpixel** [comment]
Thanks @ashleijo - sorry I didn't think to look in the lambdanotes/README.md file.

❤️ that you deployed your website!!!!!!!!!

**Pull request closed without merging**
