### PR TITLE
Kevin Chan - front-end-project - Work In Progress

### PR DESCRIPTION
**Pull request by sirkevinc**
## Trello Set Up:
* [x] Create a Trello account
* [x] Create a new board called "Lambda Notes - {Your Name}"
* [x] Create lists titled `backlog`,`To Do`, `In Progress`, and `Done`
* [x] Fill in the `To Do` list with the MVP features listed below
* [x] Fill in the `backlog` list with all the extra features listed below
* [x] Share your board with the Project Manager that has been assigned to you.  If you have not been assigned yet, reach out to your lead TA for guidance
* [x] Add your Trello URL to your project's README.md file. Commit the change, push it to your repository & submit a pull request

## MVP Features:
* [x] Display a list of notes
* [x] Create a note with a title and content
* [x] View an existing note
* [x] Edit an existing note
* [x] Delete an existing note

### CODE REVIEW

**Comment by mixelpixel** [comment]
I ❤️ your Git commit messages - very concise, easy to navigate and most importantly, meaningful 🏆

**Comment by mixelpixel** [comment]
I've added the Trello Set-up steps to your first PR comment and checked off the ones I see completed. Josh added these to the project README.md after releasing the Lambda School GitHub repo to the class.

You don't **_need_** the update to the Lambda School repositories README.md in your project, but, as far as GIT is concerned, do you have a clear vision of _**how**_ you might use Git to "add" to your local repository another "remote" alias for the Lambda School GitHub URL, such that you could `git pull upstream master` or if you prefer, `git pull lambda master`?

**Comment by sirkevinc** [comment]
I just saw the additions that Josh made with the Trello Set-up steps and made the appropriate changes to my board and included a link in my README.md.

I also pulled the changes to the Lambda School repository's README.md by adding the LambdaSchool URL to my local repository as another "remote" alias and then pulling from it.

**Comment by mixelpixel** [comment]
@sirkevinc  Awesome 🎉  would you be so kind as to add your Trello URL to the Readme.md fils and update the task list at the top of this PR?

Also, on Wednesday morning, could you DM Manisha Lal to review your MVP?

Thanks man, keep up the great work 👍

**Pull request closed without merging**
