### PR TITLE
Tyson Williams - Lambda Notes

### PR DESCRIPTION
**Pull request by tysonwilliams**
## Trello Set Up:
* [x] Create a Trello account
* [x] Create a new board called "Lambda Notes - {Your Name}"
* [x] Create lists titled `backlog`,`To Do`, `In Progress`, and `Done`.
* [x] Fill in the `To Do` list with the MVP features listed below
* [x] Fill in the `backlog` list with all the extra features listed below
* [x] Share your board with the Project Manager that has been assigned to you.  If you have not been assigned yet, reach out to your lead TA for guidance.
* [x] Add your Trello URL to your project's README.md file. Commit the change, push it to your repository & submit a pull request

## MVP Features:
* [x] Display a list of notes
* [ ] Create a note with a title and content
* [ ] View an existing note
* [ ] Edit an existing note
* [ ] Delete an existing note

### CODE REVIEW

**Comment by mixelpixel** [comment]
How's the project coming along?

When you get a minute, could you add me to your Trello board? The link I have is private: https://trello.com/b/BMUhmukZ Thanks!

I've added the Trello Set-up steps to your first PR comment. You can check-off the ones you've completed. Josh added these to the project README.md after releasing the Lambda School GitHub repo to the class.

You don't **_need_** the update to the Lambda School repositories README.md, but do you have a clear vision of _*how*_ you might use Git to "add" to your local repository another "remote" alias for the Lambda School GitHub URL, such that you could `git pull upstream master` or if you prefer, `git pull lambda master`?

**Comment by mixelpixel** [comment]
I ❤️ that you've added a background image to your Trello board. This kind of attention to the little details demonstrates your awareness of the impact that Front-End work and graphic design have on the user experience (UX)

**Comment by mixelpixel** [comment]
## THOUGHTS ON GIT COMMIT MESSAGES.

1. Git commit message titles _tell the story of your development process_. Making commits regularly is a fantastic habit to develop and regular practice to get into. No one is expecting the Great American Novel here, but succinct _Hemingway-esque_ prose describing the state of your project as you construct discrete modules, functions, add features, _et cetera_ will
    - Help your analytical thinking.
    - Let your development team quickly assess your work
    - Help you find stuff you may have worked over which you might want to revisit

2. It is GREAT that you are committing often. If you want to add additional comments and details to your git commit messages, you can **add a body to your commit messages** by adding a "newline" after the title and then all the additional info you care to include, e.g.

```
Git commit TITLE less than 50 (to 72) characters.

Git commit BODY which can contain as much pertinent information and descriptions as you see fit. Some development teams like tons and tons of information, and depending on the scope of the commit, it may be necessary to make lots of deatiled notes - especially in projects like React where there can be a vast amount of files and a complex architecture.
1) I did this
2) I did that
3) this worked well
4) this didn't
5) et alii
```

If you follow the above format, your `git log` will be easier to read, and, on GitHub in the Pull Requests, the body will be accessible by clicking on the three little dots:

screen shot 2018-02-10 at 9 06 14 pm

...such that they will reveal the BODY. This let's teammates, project leads, managers, as well as TAs Instructors, your classmates and whomever quickly evaluate your development process; your investigation; _your thinking_ - and if need be, dive in a little deeper. Also, this practice will really help _your thinking_ and _your recall_ after you've stepped away from a project for days or weeks or months and years.

screen shot 2018-02-10 at 9 06 32 pm

**Comment by tysonwilliams** [comment]
@mixelpixel Got the view to render a basic list of notes (with notes coming from a mock database imported from a notes file). Thanks! Going to use commit title and body more often! :)

**Pull request closed without merging**
