### PR TITLE
Tiffany Robbins

### PR DESCRIPTION
**Pull request by lillialskye**
## Trello Set Up:
* [x] Create a Trello account
* [x] Create a new board called "Lambda Notes - {Your Name}"
* [x] Create lists titled `backlog`,`To Do`, `In Progress`, and `Done`
* [x] Fill in the `To Do` list with the MVP features listed below
* [x] Fill in the `backlog` list with all the extra features listed below
* [x] Share your board with the Project Manager that has been assigned to you.  If you have not been assigned yet, reach out to your lead TA for guidance
* [x] Add your Trello URL to your project's README.md file. Commit the change, push it to your repository & submit a pull request

## MVP Features:
* [ ] Display a list of notes
* [ ] Create a note with a title and content
* [ ] View an existing note
* [ ] Edit an existing note
* [ ] Delete an existing note

### CODE REVIEW

**Comment by mixelpixel** [comment]
Hi @lillialskye,
I added it just now, but in the future would you be so kind as to add your name to the title of your PR?

**Comment by mixelpixel** [comment]
Hope you are feeling well today.

I also put the Trello and MVP task lists in the first comment of the PR. Is a nifty little thing GitHub does - now in the main PR list, there's a progression bar to show how far along the project is 😄

**Comment by lillialskye** [comment]
Tiffany Robbins
Reset Trello

**Comment by lillialskye** [comment]
Tiffany Robbins
-started over
-don't have the columns styling yet
-created 4 note boxes grey color but on the left side not under your notes

**Comment by lillialskye** [comment]
Tiffany Robbins
-created boxes 
-project is the wrong color
-still can't create a note
-project is a failure

**Comment by lillialskye** [comment]
Tiffany Robbins
-links created 
-notes still not created
-styling poor

**Comment by lillialskye** [comment]
finally working

**Comment by lillialskye** [comment]
deleted extra files

**Comment by lillialskye** [comment]
test added

**Pull request closed without merging**
