### PR TITLE
Amanda Phillips - Front End Project

### PR DESCRIPTION
**Pull request by astacy-phillips**
## Trello Set Up:
* [x] Create a Trello account
* [x] Create a new board called "Lambda Notes - {Your Name}"
* [x] Create lists titled `backlog`,`To Do`, `In Progress`, and `Done`.
* [x] Fill in the `To Do` list with the MVP features listed below
* [x] Fill in the `backlog` list with all the extra features listed below
* [x] Share your board with the Project Manager that has been assigned to you.  If you have not been assigned yet, reach out to your lead TA for guidance.
* [x] Add your Trello URL to your project's README.md file. Commit the change, push it to your repository & submit a pull request

## MVP Features:
* [x] Display a list of notes
* [ ] Create a note with a title and content
* [ ] View an existing note
* [ ] Edit an existing note
* [ ] Delete an existing note

### CODE REVIEW

**Comment by mixelpixel** [comment]
@astacy-phillips Good morning. Thank you for including the Task List in your first PR comment. I ❤️ that you are making frequent, meaningful Git commit messages, AND that you are updating your Trello board. You get an "Up and Running" gold ⭐️.

## THOUGHTS ON GIT COMMIT MESSAGES.

1. I ❤️ how you let your git commit message titles _tell the story of your development process_. This is a fantastic habit to develop and regular practice to get into. No one is expecting the Great American Novel here, but this kind of succinct _Hemingway-esque_ prose describing the state of your project as you construct discrete modules, functions, add features, _et cetera_ will
    - Help your analytical thinking.
    - Let your development team quickly assess your work
    - Help you find stuff you may have worked over which you might want to revisit

2. It is GREAT that you are committing often. If you want to add additional comments and details to your git commit messages, you can **add a body to your commit messages** by adding a "newline" after the title and then all the additional info you care to include, e.g.

```
Git commit TITLE less than 50 (to 72) characters.

Git commit BODY which can contain as much pertinent information and descriptions as you see fit. Some development teams like tons and tons of information, and depending on the scope of the commit, it may be necessary to make lots of deatiled notes - especially in projects like React where there can be a vast amount of files and a complex architecture.
1) I did this
2) I did that
3) this worked well
4) this didn't
5) et alii
```

If you follow the above format, your `git log` will be easier to read, and, on GitHub in the Pull Requests, the body will be accessible by clicking on the three little dots:

screen shot 2018-02-10 at 9 06 14 pm

...such that they will reveal the BODY. This let's teammates, project leads, managers, as well as TAs Instructors, your classmates and whomever quickly evaluate your development process; your investigation; _your thinking_ - and if need be, dive in a little deeper. Also, this practice will really help _your thinking_ and _your recall_ after you've stepped away from a project for days or weeks or months and years.

screen shot 2018-02-10 at 9 06 32 pm

**Comment by mixelpixel** [comment]
I also added the Trello Set-up steps to your first PR comment and checked off the ones I see completed.

You don't need the update to the Lambda School repositories README.md, but do you have a clear vision of _*how*_ you might "add" to your local repository another "remote" alias for the Lambda School GitHub URL, such that you could `git pull upstream master` or if you prefer, `git pull lambda master`?

**Comment by mixelpixel** [comment]
If you would be so kind as to add your Trello link to the project readme, you can go ahead and check off the last of the Trello task items 🏆 

Lastly, it looks like maybe you ran `yarn` in the root director of the project to install "prettier" - are you using it there? If not, you can delete:
/front-end-project-week-master/package.json
/front-end-project-week-master/yarn.lock

I don't know much about the prettier package. Ignore me if it's useful to ya (I'd be just as interested to hear how you are using it 😄 ) For displaying JSON data in a more human readable format from a server, I use the Chrome plugin PrettyPrint:
https://chrome.google.com/webstore/detail/prettyprint/nipdlgebaanapcphbcidpmmmkcecpkhg?hl=en

::google "npm prettier"::

https://www.npmjs.com/package/prettier

Oh, nice! 😃

**Comment by astacy-phillips** [comment]
My Trello link is in the readme already, I put tn in this morning. I use prettier to help me with my formatting. It just makes it prettier in places that I may have forgotten, for uniformity.

**Comment by mixelpixel** [comment]
@astacy-phillips my bad! Yep... there it is, right under that part that says Trello Link! I'll update your Task list up there in the First PR comment, and _voila_

screen shot 2018-02-27 at 11 27 36 pm

Thanks for teaching me about Prettier 😄

**Comment by satishvattikuti** [comment]
Hey, Great Going.  You have a create note button working.  The form is yet to be fuctional, I believe you are still working on it. Great organization of code. Keep up the good work.  you are commiting it often and that's awesome. Please update the task list in the Pr for me, Thanks.

**Pull request closed without merging**
