### PR TITLE
Ala Ayaad CS7 -initial commit

### PR DESCRIPTION
**Pull request by ala2233**
## MVP Features:
* [ ] Display a list of notes
* [ ] Create a note with a title and content
* [ ] View an existing note
* [ ] Edit an existing note
* [ ] Delete an existing note

### CODE REVIEW

**Comment by ala2233** [comment]
## MVP Features:
* [ ] Display a list of notes
* [ ] Create a note with a title and content
* [ ] View an existing note
* [ ] Edit an existing note
* [ ] Delete an existing note

**Comment by mixelpixel** [comment]
@ala2233 I added the MVP Task list to your _first_ PR comment - that way it will get displayed in the main PR list:

cool

Check it out:
https://github.com/LambdaSchool/front-end-project-week/pulls

**Comment by ala2233** [comment]
thank you i didnt know it will show up like this... fancy 👍

**Comment by mixelpixel** [comment]
Cool, right?

**Pull request closed without merging**
