### PR TITLE
Eileen's front-end-project progress

### PR DESCRIPTION
**Pull request by algorithmsrock**
## MVP Features:
* [x] Display a list of notes
* [x] Create a note with a title and content
* [x] View an existing note
* [ ] Edit an existing note
* [ ] Delete an existing note

### CODE REVIEW

**Comment by wlharvey4** [comment]
Eileen,
I am reviewing everyone's progress this morning.  You have only two commits posted, so there is nothing new for me to review since yesterday.  I know you will be receiving some instruction on styling today.  Try to get the functionality working first, then come back to do the styling.  Make some commits to show your progress!

Keep up the good work,
Wesley

**Comment by mixelpixel** [comment]
Eileen,

I updated your first PR comment with the following text:

```
## MVP Features:
* [ ] Display a list of notes
* [ ] Create a note with a title and content
* [ ] View an existing note
* [ ] Edit an existing note
* [ ] Delete an existing note
```

This will now display a progression bar next to your name in the main PR list:

screen shot 2018-02-28 at 12 07 50 am

Please update this Task list by checking off the items as you complete them. Thank you.

**Comment by mixelpixel** [comment]
Regarding your commit message:

> Update New Notes code set up npm start not working for my server so cannot test it

If the Node Package Manager command, `npm start` is not working, did you try `yarn start`?

**Comment by algorithmsrock** [comment]
Actually my issue was that I was trying to route axios to a server that didn’t exist. That’s why npm start wasn’t working.

**Comment by mixelpixel** [comment]
😂

**Comment by algorithmsrock** [comment]
Yeah I forgot to create one lol. After I did that, it worked exactly as I wanted it to.

**Comment by mixelpixel** [comment]
Great. Please _**COMMIT**_ your work _**often**_ and _**PUSH**_ the commits to update this PR.

**Pull request closed without merging**
