### PR TITLE
Front End Project

### PR DESCRIPTION
**Pull request by faulkenfett11**
Initial commit

## Trello Set Up:
* [x] Create a Trello account
* [x] Create a new board called "Lambda Notes - {Your Name}"
* [x] Create lists titled `backlog`,`To Do`, `In Progress`, and `Done`
* [x] Fill in the `To Do` list with the MVP features listed below
* [x] Fill in the `backlog` list with all the extra features listed below
* [x] Share your board with the project manager that has been assigned to you.  If you have not been assigned yet, reach out to your lead TA for guidance
* [x] Add your Trello URL to your project's README.md file.  Commit the change, push it to your repository & submit a pull request

## MVP Features:
* [x] Display a list of notes
* [x] Create a note with a title and content
* [x] View an existing note
* [ ] Edit an existing note
* [ ] Delete an existing note

### CODE REVIEW

**Comment by faulkenfett11** [comment]
## Trello Set Up:
* [ ] Create a Trello account
* [ ] Create a new board called "Lambda Notes - {Your Name}"
* [ ] Create lists titled `backlog`,`To Do`, `In Progress`, and `Done`
* [ ] Fill in the `To Do` list with the MVP features listed below
* [ ] Fill in the `backlog` list with all the extra features listed below
* [ ] Share your board with the project manager that has been assigned to you.  If you have not been assigned yet, reach out to your lead TA for guidance
* [ ] Add your Trello URL to your project's README.md file.  Commit the change, push it to your repository & submit a pull request

## MVP Features:
* [ ] Display a list of notes
* [ ] Create a note with a title and content
* [ ] View an existing note
* [ ] Edit an existing note
* [ ] Delete an existing note

**Comment by faulkenfett11** [comment]
got notes to display, made side bar, did some styling thus far

**Comment by faulkenfett11** [comment]
added components and routing for the notes list and create note...also have an edit notes page just not hooked up to anything.  moving on to functionality of create note and then will make buttons functional

**Comment by faulkenfett11** [comment]
it's functional...but the dilemma is, that it isn't assigning it an id...gotta do some figuring out on how to fix that...but for now going to move on to view note and edit/delete

**Comment by faulkenfett11** [comment]
took a new approach...built out server, using react and redux...already displaying notes

**Comment by faulkenfett11** [comment]
it works, it works, it finally works!  Notes are displayed, can be created, and can be clicked on to view a single note...now just have to work on edit and delete, the delete modal, and functionality of them.  Starting Delete first.

**Comment by DonnieU** [comment]
- _Need to add *axios* to your `package.json` so that *axios* is installed automatically.

- Great commit messages w/ sufficient number of commits.

- UI meets design requirements. All implemented features work. Good file and directory structure layout for both React components and Redux actions and reducers. Nice use of BEM.

- curious specificity for className deleteButton in your NoteView.js. o_O

- Code is clean and on-point. Good use of classes and necessary methods.

- Good use of your Trello board and keeping it updated. Try to breakdown each to-do into a list of tasks as you may find that helpful in your design and thought process.

Suggestion: Be able to implement this project using Vanilla JS, React, and React/Redux as 3 separate projects to really showcase your knowledge.

Great work!

Rating (0-3): 2

**Pull request closed without merging**
