### PR TITLE
Glenn-David Daniel - Initial commit

### PR DESCRIPTION
**Pull request by d2rd**
## Trello Set Up:
* [x] Create a Trello account
* [x] Create a new board called "Lambda Notes - {Your Name}"
* [x] Create lists titled `backlog`,`To Do`, `In Progress`, and `Done`
* [x] Fill in the `To Do` list with the MVP features listed below
* [x] Fill in the `backlog` list with all the extra features listed below
* [x] Share your board with the Project Manager that has been assigned to you.  If you have not been assigned yet, reach out to your lead TA for guidance
* [ ] Add your Trello URL to your project's README.md file. Commit the change, push it to your repository & submit a pull request

## MVP Features:
* [ ] Display a list of notes
* [ ] Create a note with a title and content
* [ ] View an existing note
* [ ] Edit an existing note
* [ ] Delete an existing note

### CODE REVIEW

**Comment by mixelpixel** [comment]
How's the project coming along?

**Comment by mixelpixel** [comment]
Glad we got a chance to talk one on one. I look fwd to the results of your investigations today. Good luck treading water with no concrete to stand on 😉

**Comment by mixelpixel** [comment]
Hi @d2rd - I added the Trello Set Up Task list to the first comment of your PR and checked off the appropriate items. Nice feature of GitHub is that with the task list in your first comment, there is now a progression bar next to your PR in the main list:

screen shot 2018-02-27 at 11 14 35 pm

Pretty cool huh?

If you would be so kind as to add your Trello link to the Readme.md file, you can check off that last item 🏆 Also - any reason _**not**_ to make your Trello URL public? Great way to show off your skills with time and project management using the Agile methodology 🎉

**Comment by mixelpixel** [comment]
Heya - DM'd you in Slack, just curious why the 2nd PR?

**Comment by d2rd** [comment]
Started over. Zipped my local repo then deleted the original fork.  Reforked with fresh code.

On these challenges I get myself in trouble by thinking I understand how to use some existing code.  I copy it and paste it in where THINK it goes, it blows up, then I get caught up in a loop of trying to force fit components that more than like were designed with conflicting approaches. It becomes a deep ?? hole and I get visually confused about what the original code looked like and what I changed along the way.  I've wasted days oof dev time doing that.  I finally learned another way.  Below is what I explained to Manisha this morning:

SLACK MESSAGE:
Started over yesterday.  Zipped my local repo, deleted my remote and re-forked the project.

I also created an architecture doc to plan what I need to build.  I sent this a minute ago.

All along I have been visually confused about how React components interact with each other (control flow). Especially between files. I've been trying to develop a mental map since week 1.

Yesterday, I destructured the boilerplate tag-by-tag and finally had a breakthrough on getting objects to the browser.  I have a row of three notes showing up.  They have rough styling but need adjustment.  I'll fix them when I start to paint and chrome the UI.

Today, I will:

* complete my rough layout by getting the nav and note panels to render,

* flesh out each view into a component.

* figure out how to call each view

* create a dummy dataset as a JSON array.

* refactor to use the array data

* come up for air and see what I have budget for.

I have medical appointment jn 30 mins.  will be back online by noon. "Slack you later"
-d2rd
Glenn-David Daniel


Two key behavioral changes:

1) Analyze the project and produce a written Dev plan.  Even if it's as the simple component hierarchy I created for this one.

2) Find a working model and deconstruct it by changing one line at a time.  When it crashes backup 1 step and figure out why.  This is how I had the breakthrough yesterday on control flow.  I have spent 3 weeks trying to puzzle through it visually but not 'seeing' the well lit path.

Its so funny to me how once I see the flow things seem to just click into place.  Something like the Legend of Bagger Vance (my favorite golf movie).

Today I moved forward on layout code.  Tonight I'm reviewing how control is passed between modules.  I just answered my own question about separate component files.  When I asked it I didn't  understand control flow enough.  I'm at the point now that I believe I'll have it by watching the Udemy segment a couple of more times.

Thanks for asking Patrick.  I'm going to make one dangerous Technical Product Manager when I'm done here.
Best
d2rd
________________________________

**Pull request closed without merging**
